CREATE TABLE "music_generartions" (
  "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
  "username" VARCHAR(255),
  "link_to_music_on_server" VARCHAR(255),
  PRIMARY KEY("id")
);

CREATE TABLE "image_generartions" (
  "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
  "username" VARCHAR(255) ARRAY,
  "link_to_image_on_server" VARCHAR(255),
  PRIMARY KEY("id")
);

CREATE TABLE "users" (
  "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
  "username" VARCHAR(255),
  "email" VARCHAR(255),
  "hashedpassword" VARCHAR(255),
  PRIMARY KEY("id")
);

CREATE TABLE "text_generartions" (
  "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
  "username" VARCHAR(255),
  "link_to_txtfile_on_server" VARCHAR(255),
  PRIMARY KEY("id")
);

ALTER TABLE "users"
ADD FOREIGN KEY("username") REFERENCES "text_generartions"("username")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "users"
ADD FOREIGN KEY("username") REFERENCES "image_generartions"("username")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "users"
ADD FOREIGN KEY("username") REFERENCES "music_generartions"("username")
ON UPDATE NO ACTION ON DELETE NO ACTION;
