services:
  name: cumBack-API
  cumBack-API:
    image: python
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    volumes:
      - .:/api
    ports:
      - 8000:8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000

volumes:
  home:
